kind: live

defaults:
  preset: gpu-k80-small-p
  life_span: 1d

volumes:
  code:
    remote: storage:$[[ flow.project_id ]]/modules
    mount: /project/code
    local: modules
  config:
    remote: storage:$[[ flow.project_id ]]/config
    mount: /project/config
    local: config
  scripts:
    remote: storage:$[[ flow.project_id ]]/scripts
    mount: /project/scripts
    local: scripts
  results:
    remote: storage:$[[ flow.project_id ]]/results
    mount: /project/results
    local: results
  data:
    remote: storage:$[[ flow.project_id ]]/data
    mount: /project/data
    local: data
  project:
    remote: storage:$[[ flow.project_id ]]
    mount: /project
    local: .

images:
  myimage:
    ref: image:$[[ flow.project_id ]]
    dockerfile: $[[ flow.workspace ]]/Dockerfile
    context: $[[ flow.workspace ]]/
    build_preset: cpu-medium

jobs:

  remote_debug:
    action: gh:neuro-actions/remote_debug@v1.0.0
    args:
      image: $[[ images.myimage.ref ]]
      volumes_data_remote: $[[ volumes.data.remote ]]
      volumes_code_remote: $[[ volumes.code.remote ]]
      volumes_config_remote: $[[ volumes.config.remote ]]
      volumes_results_remote: $[[ volumes.results.remote ]]

  train:
    image: $[[ images.myimage.ref ]]
    detach: False
    life_span: 10d
    volumes:
      - $[[ volumes.data.ref_ro ]]
      - $[[ volumes.code.ref_ro ]]
      - $[[ volumes.config.ref_ro ]]
      - $[[ volumes.results.ref_rw ]]
      - $[[ volumes.project.ref ]]
    env:
      EXPOSE_SSH: "yes"
      PYTHONPATH: $[[ volumes.code.mount ]]
    bash: |
        cd $[[ volumes.project.mount ]]
        python -u $[[ volumes.code.mount ]]/train.py --data $[[ volumes.data.mount ]]

  multitrain:
    image: $[[ images.myimage.ref ]]
    detach: False
    life_span: 10d
    volumes:
      - $[[ volumes.data.ref_ro ]]
      - $[[ volumes.code.ref_ro ]]
      - $[[ volumes.config.ref_ro ]]
      - $[[ volumes.results.ref_rw ]]
    env:
      EXPOSE_SSH: "yes"
      PYTHONPATH: $[[ volumes.code.mount ]]
    multi: true
    bash: |
        cd $[[ volumes.project.mount ]]
        python $[[ volumes.code.mount ]]/train.py --data $[[ volumes.data.mount ]] $[[ multi.args ]]

  jupyter:
    action: gh:neuro-actions/jupyter@v1.0.0
    args:
      image: $[[ images.myimage.ref ]]
      preset: gpu-k80-small-p
      multi_args: $[[ multi.args ]]
      volumes_data_remote: $[[ volumes.data.remote ]]
      volumes_code_remote: $[[ volumes.code.remote ]]
      volumes_config_remote: $[[ volumes.config.remote ]]
      volumes_notebooks_remote: $[[ volumes.notebooks.remote ]]
      volumes_results_remote: $[[ volumes.results.remote ]]

  tensorboard:
    action: gh:neuro-actions/tensorboard@v1.0.0
    args:
      volumes_results_remote: $[[ volumes.results.remote ]]

  filebrowser:
    action: gh:neuro-actions/filebrowser@master
    args:
      volumes_project_remote: $[[ volumes.project.remote ]]
  
  distributed_training:
    image: $[[ images.myimage.ref ]]
    name: $[[ params.name ]]
    life_span: 1d
    multi: true
    detach: true
    volumes:
      - $[[ volumes.code.ref_ro ]]
      - $[[ volumes.scripts.ref_ro ]]
      - $[[ volumes.config.ref ]]
      - $[[ volumes.results.ref ]]
      - $[[ volumes.data.ref ]]
      - $[[ volumes.project.ref ]]
    params:
      world_size: "2"
      local_rank: "0"
      master_ip: "0"
      master_port: "9080"
      name: ~
    env:
      EXPOSE_SSH: "yes"
      PYTHONPATH: $[[ volumes.project.mount ]]
      LOCAL_RANK: $[[ params.local_rank ]]
      WORLD_SIZE: $[[ params.world_size]]
      MASTER_IP: $[[ params.master_ip]]
      MASTER_PORT: $[[ params.master_port ]]
    bash: |
      cd $[[ volumes.project.mount ]] && $[[ volumes.scripts.mount ]]/worker.sh -c $[[ volumes.config.mount ]]/test_bert.cfg

